sudo: required
dist: trusty
language: python
cache: pip
matrix:
    include:
        - python: 2.7
        # - python: 3.5
        # - python: 3.6
before_install:
  - sudo apt-get update
install:
  - echo $(python --version)
  - curl -s https://gist.githubusercontent.com/lukedeo/58b4b9cb75d9d62817829b2afa900ac3/raw/a2bbb2fa0cade9885ac343fbc6766586ac5a5b9c/build-leveldb.sh | sudo sh -
  - sudo pip install -e .[all,tests]
  - wget http://download.redis.io/releases/redis-3.2.8.tar.gz && \
    tar xzf redis-3.2.8.tar.gz && \
    cd redis-3.2.8 && \
    make
  - nohup src/redis-server &> /tmp/redis.log &
# command to run tests
script:
  # run keras backend init to initialize backend config
  - py.test test/
  
# after_success:
#   - coveralls